import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const root='public';
function walk(p){return fs.readdirSync(p).sort().flatMap(n=>{const f=path.join(p,n);return fs.statSync(f).isDirectory()?walk(f):[f];});}
const files=walk(root).filter(f=>!f.endsWith('/sw.js'));
const hash=crypto.createHash('sha256');for(const f of files)hash.update(fs.readFileSync(f));
const version=hash.digest('hex').slice(0,16);
const urls=['./',...files.map(f=>'./'+path.relative(root,f).replaceAll('\\','/'))];
fs.writeFileSync('public/sw.js',`// Generated by scripts/build.mjs; content-addressed cache.\nconst CACHE='sahaya-${version}';\nconst URLS=${JSON.stringify(urls)};\nself.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(URLS)));});\nself.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('sahaya-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));\nself.addEventListener('fetch',event=>{if(event.request.method!=='GET'||new URL(event.request.url).origin!==self.location.origin)return;event.respondWith(caches.match(event.request).then(cached=>cached||fetch(event.request)));});\n`);
console.log(`Build OK: ${files.length} bundled files; offline cache sahaya-${version}`);
